version: '3.8'

services:
  # --- O BANCO ORACLE ---
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: meu-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123          # Senha do admin (SYSTEM)
      - APP_USER=Yuri                # <--- MUDAMOS AQUI
      - APP_USER_PASSWORD=123        # <--- MUDAMOS AQUI
    volumes:
      - oracle-data:/opt/oracle/oradata

  # --- O SEU SITE ---
  oraculo-app:
    build: .
    container_name: meu-site
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=Yuri  # <--- TEM QUE SER IGUAL AO DO BANCO
      - SPRING_DATASOURCE_PASSWORD=123   # <--- TEM QUE SER IGUAL AO DO BANCO
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - oracle-db

volumes:
  oracle-data: